### ISSUE TITLE
mqtt support

### ISSUE THREAD

**Issue by funlike1** [dev-lab/esp-thermal-camera-streamer#1]
Hi. 

Great project! It´s a perfect and cost-effective method for testing electronic components. 

Another application would be to use it as a stationary sensor for home automation. For example, monitoring the DYI home storage battery.

Useful sensor data that could be made available via mqtt (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mqtt.html):
- Current maximum temperature
- Current minimum temperature
- Current mean temperature value (optional)
- Rapid rise in average temperature by x degrees (optional)

Cheers
Martin

**Comment by dev-lab** [comment]
Hi Martin,

Thank you for the positive feedback!

As for sending sensor data to MQTT, that would be a much simpler project compared to the existing one, I don't see any challenges there. But this functionality goes beyond my philosophy of making this project self-sufficient (without dependencies on other services).

Alternatively, you can create an adapter for an existing Thermal Camera Streamer. That would be http client, listening for frames at /stream, processing them according to your business logic, and sending detected events to kafka, NATS, 0MQ, or any other messaging system you have.

Best regards,
Taras.

**Comment by oficjalniebktv** [comment]
Hello, the program does not see my camera and when I click setup nothing happens
![IMG20240128130324](https://github.com/dev-lab/esp-thermal-camera-streamer/assets/154439292/2c017484-50c6-44c1-85ec-ca91d2fcace8)
![IMG_20240128_131154](https://github.com/dev-lab/esp-thermal-camera-streamer/assets/154439292/735a73a5-e6cb-4884-9290-ce466a6eefcd)

**Comment by dev-lab** [comment]
The BOM clearly states a GY-MCU90640 module, not a pure MLX90640 sensor. GY-MCU90640 communicates over serial interface, not over I2C.

**Comment by oficjalniebktv** [comment]
Da się coś z tym zrobić żeby działało poprawnie ?
